### ISSUE TITLE
report the log about Mesh import failed

### ISSUE THREAD

**Issue by Menzex** [ross-g/io_pdx_mesh#10] opened 2020-02-05 07:56 UTC
Mesh import failed!
'NoneType' object has no attribute 'inputs'

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 387, in execute
    bonespace=self.chk_bonespace
  File "C:\Users\86130\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1122, in import_meshfile
    create_material(pdx_material, mesh, os.path.split(meshpath)[0])
  File "C:\Users\86130\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 671, in create_material
    shader = create_shader(PDX_material, shader_name, texture_path)
  File "C:\Users\86130\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 624, in create_shader
    links.new(albedo_texture.outputs['Color'], shader_root.inputs['Base Color'])
AttributeError: 'NoneType' object has no attribute 'inputs'

location: <unknown location>:-1

**Comment by ross-g** [comment] 2020-02-05 22:09
Duplicate of #8

**Closed by ross-g** 2020-02-05 22:09 UTC
