### ISSUE TITLE
Addon fail to load on blender 2.93.4 on mandjaro 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ross-g/io_pdx_mesh#60] opened 2021-09-19 19:55 UTC
Activation attempt of addon show following error
```
Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/ktoto/.config/blender/2.93/scripts/addons/io_pdx_mesh/__init__.py", line 131, in <module>
    raise NotImplementedError('Running from unknown environment "{0}"'.format(environment))
NotImplementedError: Running from unknown environment "/usr/bin/python3.9"
```

Python version : 
Python 3.9.7

After some investigations i found that in "io_pdx_mesh" used 
method : environment = sys.executable.lower() 
but because precess tree look like this : bash -> blender -> python 3.9 -> python script 
Result contain : "/usr/bin/python3.9"
May be is an option to use : https://github.com/giampaolo/psutil intead of sys.executable

**Comment by ross-g** [comment] 2021-09-19 22:43
Happily this has already been fixed in the Bugfixes branch. (duplicate of #45)

Please download and use that version ahead of it being properly released.

**Closed** 2021-09-19 22:43 UTC
Labels: duplicate
